### ISSUE TITLE
Show mod and vanilla conflicts

### ISSUE THREAD

**Issue by bcssov** [bcssov/IronyModManager#11]
From Reddit:

> Thanks for the response.
> 
> My workflow would be "wanting to predict the intrusiveness of a new mod." I find mods that override a lot of vanilla items are likely to have conflicts or integrate poorly with other mods. It would also help when predicting robustness of the mod against version changes and in updating to new patches. For UI Overhaul it wouldn't be useful, I agree. A good example would be a Civic Pack: these can range from using mostly modifiers to editing most buildings and pop jobs in the vanilla game and it's nice to know this in advance.
> 
> It's not an urgent feature of course and even without it there'd be workarounds to do the same thing, but for me it would be nice

**Comment by calniotrey** [comment]
I think it shouldn't be the default behavior. So there should be an option to take vanilla into account, b default off. Maybe having a checkbox in the collection area "Include vanilla". Then the workflow would be :

1. Create a new collection
2. Add the mod and check the checkbox
3. Look at the conflict between the mod and vanilla

Maybe just a context "option" in the installed mod area that would directly do open the conflict solver for selected mod(s) and vanilla.

**Comment by LordOfLA** [comment]
ooh, actually I think right-click mod > compare to vanilla then you can patch accordingly. Whether that gets bundled into the mod itself or the collection patch mod I dunno.

**Comment by bcssov** [comment]
I was thinking too about using a context menu option that would be available in installed mods and collection mods area. But the reason why I put it in vNext is because I've no clue what to do with merged content? Or should this just generate patch diffs? Or the whole thing would just be readonly? I am tempted to plan this for 1.1 but without any ideas how the conflict solver should behave on this matter is problematic.

**Comment by calniotrey** [comment]
I would say read-only if it is a steam workshop mod, or patch directly into the mod files if it is a local mod (for modders to do some quick update once a stellaris update hits).

**Comment by bcssov** [comment]
That works. I already have all of that:
1. I already detect Local, Pdx, Steam sources
2. Patch export already accepts paths where to export stuff 

Moving to 1.1 roadmap.

Note to self: Modify export to dump a whole file rather than a single definition in case of vanilla conflict solving.

**Comment by Archemedes** [comment]
Maybe something simpler related to this when the ability to check vanilla defs is implemented: Auto-Ignore conflicted defs if one of the mods' defs is identical to vanilla.

Mods override 0x_y_jobs.txt (because stellaris requires this for jobs) and 0x_static_modifiers.txt (because they dont know its FIOS). This leads to faux conflicts where 1 version is just vanilla. In those cases the other version can be taken automatically.

also related to https://github.com/bcssov/IronyModManager/issues/2 but much easier to implement.

**Comment by bcssov** [comment]
I am not sure what you are suggesting. Irony already in a similar manner ignores content which does not differ, ex. 2 definitions that are the same are never shown. Or if multiple defs are detected and some are the same then only the one with the priority is chosen (ones that are the same) and the rest are taken. Therefore this suggestion would not be any easier or more difficult to implement than what was being discussed here.

**Comment by i2amroy** [comment]
Throw two cents in for providing some way to see the diff between mod entries and vanilla ones, at least in the conflict solver. Mainly since sometimes mod authors might miss a dlc or be a little late on updates after smaller vanilla patches.

I know I've had a number of times where 3+ mods are all touching the same vanilla definition and it can get very tricky to tell which diffs in each version are supposed to be actual intended mod changes that I need to merge over, and which are just there because one of the conflicts was using the pre-dlc vanilla entry instead of the post-dlc one (or doesn't include the v2.8.3 bugfix for devouring swarms, or whatever).

For the time being when I run into those I usually just revert to the pre-Irony method of running each individual file vs vanilla in an external diff editor so it's not a show stopper, but some way to see that diff information in the conflict solver itself would be extremely helpful in being able to resolve those cases more quickly.

**Comment by bcssov** [comment]
I really wish I had more help on this project.

**Comment by zedr0n** [comment]
what I've done locally at least is just add an option to include the base game as "Vanilla" mod, so it's included in the conflict viewer.
For my usage I am thinking about introducing 3-way merge using an external merge tool - so I'll add some kind of "Set Base" context menu option and then that definition will be passed on as a base version to the merge tool.

**Comment by bcssov** [comment]
Cool, now that Irony is on Avalonia 0.10.x branch I was also thinking of revisiting an inbuilt "advanced" merge editor using the following combinations:
1. Either:
    - https://github.com/CefNet/CefNet
    - https://gitlab.com/joaompneves/cefglue
    - https://github.com/OutSystems/WebView
2. https://microsoft.github.io/monaco-editor/playground.html

It would probably bloat the program size though.

**Comment by zedr0n** [comment]
the 3-way merge changes are up on my fork if you are interested. I use Beyond Compare and Irony seems to pick it up and save correctly to the patch mod after resolving. I am going to be looking into whole dump export as a way to patch the existing mods as 3.0 is coming, not sure if you've added that yet?

Chromium is so heavy, I remember trying it as a UI and it was painful. Haven't tried Monaco but it seems quite nice.
On a side note, I didn't even realise before I could edit directly in Irony, before actually going through the documentation.

**Comment by bcssov** [comment]
> I am going to be looking into whole dump export as a way to patch the existing mods as 3.0 is coming, not sure if you've added that yet?

I haven't. Which reminds me I'll need to update parser map for 3.0 and run some tests myself to see whether Irony processes game files without any issues. Regardless I'll have to probably release a new version (should not cause you any issues with merging I hope).

> Chromium is so heavy, I remember trying it as a UI and it was painful. Haven't tried Monaco but it seems quite nice.
On a side note, I didn't even realise before I could edit directly in Irony, before actually going through the documentation.

That's why I gave up on that, well that and the fact Irony was on Avalonia 0.9. Now I've recently been reconsidering things and Monaco itself is a pretty good choice IMO (it's good enough for VS Code).
