### ISSUE TITLE
Irony unable to write files when clicking "resolve"

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#120]
This is with Irony 1.6.99-rc.

When attempting to update an existing patch or create a new one (with just two mods to test) Irony pops up the red alert box that it's unable to write. Doesn't seem to be a conflict with software on my PC from the log, tested with AV temporarily disabled in case of that.

It does, however, output orphan objects so not sure what's going on there.

Error log attached.
[2020-09-26_Error.log](https://github.com/bcssov/IronyModManager/files/5286301/2020-09-26_Error.log)

**Comment by bcssov** [comment]
Going to need you launcher sqlite db attached.

**Comment by LordOfLA** [comment]
Here we go. Forgot to mention I had also deleted the entire paradox folder and had the launcher create everything fresh as a test as well.

[launcher-v2.zip](https://github.com/bcssov/IronyModManager/files/5286449/launcher-v2.zip)

**Comment by bcssov** [comment]
The background story is that the sqlite ORM component I'm using had a bug previously (well 2 or 3) that I reported to the maintainer. One of these was that it did not properly call type converters that I had declared (string to guid conversion). TLDR; Author reported one issue fixed but in the process he broke something in his code and made my type converters not being called. So since I'm getting tired of this I've just switched all model db datatypes to strings.
