### ISSUE TITLE
Add irony patch to file hash validation

### ISSUE THREAD

**Issue by OldEnt** [bcssov/IronyModManager#124]
**What:** Option switch to disable/enable Irony custom patch conflict resolutions for given collection (or globally, whatever works).

**Why:** Assures multiplayer users with imported load orders don't bork things up locally without realising it.

**How:** Irony does not show its patch mod in the loadout, but Paradox Launcher does. Perhaps an ignore patch button which disables the patch mod somewhere outside loadout window would do.

**Priority:** Lowest of the low.

**Comment by bcssov** [comment]
I'm assuming that you're talking about the patch mod because in my terminology custom patch is something you type into the conflict solver custom patches window.

Having said that and believing I'm interpreting this correctly. That's not a very practical solution, you disable on your end and the other users does not on their end then you have the same problem. There is no way to force pdx launcher to hide an enabled mod but irony patch mod is exactly that; automatically configured mod which needs to have its order set automatically (as in always last). For MP you now have in v1.7 file hash validation which should ensure that everyone has the same installs so even if you do run the conflict solver nothing will change. 

This is no silver bullet solution by any means so I'm not for it. I'm assuming this is because you are using export mod order only option, in this case it should be down to the users to not use the conflict solver and not an option in Irony really. The export order only option was added for convenience only.
