### ISSUE TITLE
Please do not use non-open compressed file format such as rar for packaging

### ISSUE THREAD

**Issue by KagurazakaNyaa** [bcssov/IronyModManager#131]
Generally speaking, the more common packaging method is to use zip under Windows/Linux, use tar.gz under Linux, and also use 7z as the packaging method, but the versatility of non-open compression formats such as rar is not like open formats so good.
Therefore, it is recommended to use zip or 7z compression format for better versatility when releasing Windows versions later.

**Comment by bcssov** [comment]
Rar might be a proprietary format but they release open source components which other software utilizes and almost any archiving utility supports it. I'll list some of the most popular windows components that I know of support it:
- 7-Zip
- Bandizip
- Peazip
And so on.

Even most up to date software on linux supports unpacking RAR archives (but for reasons that not all software uses it I switched to zip packaging for linux releases). Creating rars is a different thing, but I think I made my point. It is not uncommon also as you might think to see rar release packaging.

Now having said that, why I chose RAR instead of zip or 7z? That's relatively easy I want to save bandwidth when uploading to github as my internet connection speed is not all that great and every byte helps. One might argue that 7z is a much better choice in that case, and they'd be right but since Irony has autoupdate and now automatically downloads downloads and unpacks said packages; that means it also needs to know how to unpack 7z files and here is where my problem lies. The third party component that I use has severe performance degradation when unpacking 7z files while RARs and Zips work fine. So until this issue is resolved, I will continue to use the following setup.

**Comment by ThibautSF** [comment]
You might plan to use Github actions (or ay pipeline system), it solves me that internet bandwidth problem (avoid to upload 3 times 40-50MB) and all build/packaging related stuff.
It is pretty easy to understand and just need some tests in order to deploy.

**Comment by bcssov** [comment]
I was planning to but setting up Irony build and deployment procedure is a bit on the complex side and I do not have time to set it up at the moment
