### ISSUE TITLE
Save Error

### ISSUE THREAD

**Issue by Dillon91** [bcssov/IronyModManager#132]
[2020-10-17_Error.log](https://github.com/bcssov/IronyModManager/files/5397101/2020-10-17_Error.log)
**Describe the bug**

I consistently get an error when attempting to save any changes to the Mod order or when resolving any conflicts:

"Save Error

Something seems to be locking Irony's ability to write to mod files"

**Expected behavior**
 
To be able to save correctly. 

**Screenshots**

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: Windows 10
 - Irony Version: 1.7.49

**Additional context**

**Comment by Dillon91** [comment]
Here is the db i have as well.
[empty_paradox_launcher.zip](https://github.com/bcssov/IronyModManager/files/5397138/empty_paradox_launcher.zip)

**Comment by bcssov** [comment]
I don't know the cause of the corrupt _playsets_ table in your _launcher-v2.sqlite_ database. I only know it happens in certain instances. It would help to know what steps you took prior to getting that; for me to identify the cause and fix it.

There is a **fix** but since the cause is not known to me I cannot fix it completely at the moment. See **#128** for a fix. 

In a couple of scenarios the _playsets_ corruption was caused by users using external db editor and they corrupted their database that way, I doubt that is the cause of every report out there.

The database you posted here is not the database I'm looking for as well. That's just Irony's empty database; the one that will be copied if it finds to available databases found in Documents\Paradox Interactive\<Game>.

**Comment by Dillon91** [comment]
Thanks! That was the issue.
