### ISSUE TITLE
Override x11 Avalonia implementation

### ISSUE THREAD

**Issue by skwerlman** [bcssov/IronyModManager#133]
**Describe the bug**
GUI becomes temporarily corrupted when switching workspaces in i3wm

**To Reproduce**
1. Run on linux under i3
2. switch workspaces away from the mod manager
3. switch workspaces back to the mod manager
4. gui shows artifacts until some element of the gui changes, at which point the whole ui fixes itself

**Expected behavior**
The GUI should continue to appear as normal

**Screenshots**
![2020-10-22-182436_1288x1408_scrot](https://user-images.githubusercontent.com/6954107/96936382-ecc4ca80-1493-11eb-8cb8-7836bf5914e6.png)

**Logs**
N/A

**Version:**
 - OS: Arch Linux 5.9.1-zen2
 - Irony: 1.7.53

 - nvidia driver: nvidia-dkms 455.28
 - window manager: i3-gaps 4.18.3
 - compositor: picom 1483_8.rc2.74.gd00c1c7_2020.10.07 (picom-git)

**Additional context**
picom started with `picom --backend glx --glx-no-rebind-pixmap --glx-no-stencil --blur-background -i 0.95 --xrender-sync-fence -c`

**Comment by bcssov** [comment]
Unfortunately there's not much I can do. This is down to the Avalonia (framework I'm using). And by just looking at Avalonia issue tracker the issue is known and reported but not fixed (3460 on Avalonia issue tracker). 

But even if it's fixed that would require that I upgrade my avalonia version from 0.9.12 to 0.10 which at the moment is not an option due to a number of breaking changes (and 0.10 is still in preview; so highly unstable).

As a last resort maybe if you enable or disable one of these linux specific options I exposed in appSettings.json can at least help in some way: https://github.com/bcssov/IronyModManager/blob/master/src/IronyModManager/appSettings.json
I exposed these Avalonia settings due to many linux distros out there.

**Comment by skwerlman** [comment]
i'll experiment with those settings to see if i can find a combo which works. its not a _huge_ deal since just moving my mouse over the window is enough to fix it, so no worries there.

thanks for the pointer to the upstream issue

**Comment by bcssov** [comment]
Going to leave these extra notes for future reference.

In case upgrading to 0.10 becomes a real chore my only other option is to rip out the X11 namespace logic from Avalonia (whole code base of around 20 classes). Because they are all private and cannot be overridden. All in the effort so that I can add the following lines (and possibly 2-3 more once the issue is fully resolved):
![Image2](https://user-images.githubusercontent.com/5864390/97041300-a349ad80-156f-11eb-9783-2fde714a563d.jpg)
As mentioned in the Avalonia ticket these lines somewhat mitigate the issue but not fully resolve it, if you really try you can still reproduce the issue.

Note: I already had to rip out the logic for managed file dialogs because they were all private as well and could not be localized.
