### ISSUE TITLE
Locked ability to write

### ISSUE THREAD

**Issue by HawkeyeGreen** [bcssov/IronyModManager#145]
**Describe the bug**
So I just installed your amazing ModManager! I love it so far but whenever I try using "Apply" or to resolve Mod-Conflicts I get the Error that "Something seems to be blocking Irony's ability to write to mod files."

I tried reinstalling, making fresh new collections. Tried different installation-Locations.

**Logs**
[2020-11-08_Error.log](https://github.com/bcssov/IronyModManager/files/5506133/2020-11-08_Error.log)

**Version:**
 - OS: Windows

 - Irony Version concurrent

**Additional context**

**Comment by bcssov** [comment]
Delete one of all of these:
dlc_load.json
game_data.json
mods_registry.json
The json(s) seem to be corrupted, if you're able you can use the exception stacktrace to find where the invalid character is and attempt to fix the json manually.
```2020-11-08 11:03:45.6197 Newtonsoft.Json.JsonReaderException: Additional text encountered after finished reading JSON content: 7. Path '', line 1, position 11893.```
Irony will work fine if you don't salvage anything since it'll recreate the jsons next time it has to.
