### ISSUE TITLE
Mod manager get stuck at loading mod data indefinitely or crashes after a fatal error.

### ISSUE THREAD

**Issue by kneekokneeko** [bcssov/IronyModManager#152]
**Describe the bug**
At startup, once selecting a game, gets stuck at loading mod data. If lucky, it crashes after encountering a fatal error. If not, it is stuck indefinitely. 

**To Reproduce**
1. Run as administrator.
2. Select Game. 

**Expected behavior**
Mod data should have been read and a list of mods be generated

**Logs**
[2020-11-18_Error.log](https://github.com/bcssov/IronyModManager/files/5558318/2020-11-18_Error.log)

**Version:**
 - OS:  Windows
 - Irony Version v.1.8.60

**Additional context**
The error log indicates having no permission even if run as administrator. Furthermore, it tries to access Folders that does not exist. C;/Documents and Settings & D;/Working. And yes, I have tried looking for hidden folders.

**Comment by bcssov** [comment]
The D drive location is just a diagnostic information for me, it's the location where the source was compiled at (on a VM on my computer). So this piece of information is for me to point me to where I should look at to see which piece of code caused a crash or some other error.

As for why it's crashing it's probably because the piece of logic pointing towards your user directory on your OS is corrupt in some way. Either your environment variables are pointing to a wrong location or you could be missing C:\Documents and Settings shortcut on your OS (due to a corruption or something -- it's a hidden system file).
