### ISSUE TITLE
Hoi4 crashes

### ISSUE THREAD

**Issue by Gamrus** [bcssov/IronyModManager#157]
**Describe the bug**
When trying to start a larger mod( tested it with Kaiserreich and The New Order) Hoi4 crashes while loading and tells me 
''Failed to load the map''
''Some errors are present in the map definition and have been logged to error.log''

**To Reproduce**
1. Select Kaiserreich or The New Order(possibly other bigger mods)
2. Launch the game

**Expected behavior**
The game loads the selected mod

**Logs**
Hoi4 error log
[error.log](https://github.com/bcssov/IronyModManager/files/5637530/error.log)

**Version:**
 - OS: Windows
 - Irony Version 1.9.48

**Comment by bcssov** [comment]
For a mod manager developer game error log is useless. Once Irony launches the game it's out of my hands. What I assumed that happened is that Irony did not properly parse a descriptor.mod (and I was right). 

Paradox is once again consistently inconsistent in their logic. In this case Irony did not properly parse replace_path properties as apparently these behave as an array rather than a key value pair and seeing that they already have arrays in mod descriptors (see tags or dependencies) I cannot understand why would they break the standard.

Anyway, once you download a new version regenerate the descriptors using Irony since these are broken for the mods you mentioned. This should fix the issue but I cannot test as I don't own any PDX games except Stellaris.
