### ISSUE TITLE
Irony Mod manager crash while launching 

### ISSUE THREAD

**Issue by FuzeAntatic** [bcssov/IronyModManager#166]
After I download the lasted update of Irony, I can't seem to launch the mod manager

**Comment by bcssov** [comment]
Provide more info, check out the bug report template. Things we need: OS info, Irony log. Otherwise this ticket will be closed automatically due to insufficient information provided.

**Comment by FuzeAntatic** [comment]
OS: Windows 10
[2020-12-13_Error.log](https://github.com/bcssov/IronyModManager/files/5684235/2020-12-13_Error.log)

**Comment by bcssov** [comment]
You have a corrupt state.json a file which contains all the relevant Irony patch data. In one of your folders in mod directory prefixed with IronyModManager_[name of your collection] look for it and try restoring a backup file in the same directory called state.json.bak. If the file is damaged beyond recovery all your irony patch data is lost and next time you run the conflict solver it will be lost. 

What were the steps before this corruption occurred?

**Comment by FuzeAntatic** [comment]
I was trying to resolve conflicts between mods and it crash, seriously I don't really know what cause it to crash
Sadly I can't fix it so that means I lost all my patch data......
Anyway thanks for your help.

**Comment by bcssov** [comment]
The way you said you had to resolve 6k conflicts implies that you just hit resolve instead of actually properly merging stuff. That way you might just as better ignore conflict solver. Properly merging conflicts and checking out 6k conflicts takes days for someone familiar with win merge. 

As for the reason of the crash your logs suggest that you seem to run multiple instances of irony. That could have caused some of your problems.

Closing ticket.
