### ISSUE TITLE
Crash on start with fatal error. win-x64-v1.12.118

### ISSUE THREAD

**Issue by F1r3Pr1nc3** [bcssov/IronyModManager#204]
**Describe the bug**
On start there appear 2 fatal error popups (portable and setup version).

**Logs**
[2021-03-13_Error.log](https://github.com/bcssov/IronyModManager/files/6134461/2021-03-13_Error.log)
[2021-03-13_Error.log](https://github.com/bcssov/IronyModManager/files/6134462/2021-03-13_Error.log)

**Version:**
 - OS: Windows 7 x64
 - Irony Version 1.12.118 and above
 1.12.116 is working fine.

**Comment by bcssov** [comment]
1. Latest version is 1.12.126
2. The error means that app cannot find fonts that are supposed to be used
3. Either:
	a) Fonts folder is missing from your installation
	b) Localization <locale>.*json App.FontFamily is pointing towards a non existant font
4. Verified 1.2.118 that everything works as it should in the portable version

**Comment by bcssov** [comment]
My bad, SkiaSharp doesn't seem to like Windows 7 and doesn't load CJK fonts. To fix for 1.12 at the moment:
1. Either delete zh.json from Localization folder
2. Open zh.json and set another installed font for yourself: https://github.com/bcssov/IronyModManager/blob/e874da4d78aa92cdecb0f3215621741134c6b97b/src/IronyModManager/Localization/zh.json#L4

This will be fixed in 1.13 because I'm bumping Avalonia. There's nothing I can do for 1.12 at the moment as this piece of logic is not exposed in Avalonia 0.9 for me to override. A drawback is that chinese mod names might not render at all in the collection and installed mods area for you.

**Comment by F1r3Pr1nc3** [comment]
Nice, exactly, your advice solved it (deleting any zh)!
