### ISSUE TITLE
External editor service uses temporary filenames

### ISSUE THREAD

**Issue by ErenForce** [bcssov/IronyModManager#217]
It's a pain to go back and forth between the external editor and the application to remember which file is which on which side. Since Irony is the one creating the files and is simply passing the filenames to the external editors, there's no reason why temporary file names should be used. If unique filenames are required, well there's no reason why they should be required as the files are ~~disposed~~ deleted before the next conflict.

The two `Create()` methods used [here](https://github.com/bcssov/IronyModManager/blob/9028c2363ddb27a0549f4fdc1e803db0ed0d9b96/src/IronyModManager.Services/ExternalEditorService.cs#L77) should be passed the left filename and right filename which would come from `ExternalEditorFiles.GetFiles()` which then comes from `MainConflictSolverViewModel.LaunchExternalEditor()` which `MainConflictSolverViewModel` would get from `ModCompareSelectorControlViewModel` via `MainConflictSolverViewModel`'s self subscription to `LeftSelectedDefinition` and `RightSelectedDefinition` changes; similar to how `MergeViewer.SetText()` is called there would be a call like `MergeViewer.SetExternalEditorFilenames(string leftFilename, string rightFilename)`. At which point `$"{s.ModName} - {s.Id}"` would be passed in order to mirror the values from `DefinitionPriorityTextConverter`.

Pretty sure this works, I'm willing to do a PR tomorrow, however I know almost nothing of Irony's unit testing setup so I doubt I can make one for this.

**Comment by bcssov** [comment]
Heh, unit tests need a serious update. Kinda neglected these. There should be probably triple the amount of what currently there is (1500 instead of 500). 

The usage of temp filenames is intentional. In case irony crashed I wanted to use the temp file generation logic provided by net core. Which in the hopes of a crash, and the fact that these files would remain then, they would be deleted by the os via disk cleanup type of action. 

Though I did neglect to study the fact whether this would work on all supported os.

**Comment by ErenForce** [comment]
Ah that does make a decent use case, however the clean up logic is provided by the operating system, not net core. The location of the file is important, not the name of the file. In this case the method to use is `Path.GetTempPath()` which I assume `TempFile` uses? Yeah, it does `path = Path.Combine(TempDirectory, fileName);` For the edge case that the file would remain after a crash, there could simply be a check within `TempFile.Create()` to either wipe the temp file or delete the file and then create a new file. I agree this feels clunky so the other approach, which tends to be the most used, is to have the filename and then append a guid. I think git does something like this for merge conflicts, or maybe it was Visual Studio's conflict merger.

**Comment by ErenForce** [comment]
Template could be `{s.ModName} - {s.Id}.{shortGuidFunc()}` where `shortGuidFunc` is defined as
```
private Regex pattern = new Regex("[/+=]", RegexOptions.Compiled);
private Func<string> shortGuidFunc = () => { 
    var guid = pattern.Replace(Convert.ToBase64String(Guid.NewGuid().ToByteArray()), "");
    return new string(guid.Take(4).ToArray());
};
```
which would produce something like 
`Amazing Space Battles - adv_kinetic_artillery_entity.eRcT.tmp ↔ Downscaled Ships - adv_kinetic_artillery_entity.RCzS.tmp`
Both informative and functional as temp files. 🙂

**Comment by bcssov** [comment]
I'm not sure what exactly you mean I could delete the file if it exists? The file when is created is already overwritten by the file.create logic and is not a problem for me. This either returns an existing file or if it exists it overwrites it. So that's not an issue (or if it is it's easily remedied). 

And yes, the cleanup logic is provided by the os. But in the same manner I rely on net core to resolve environment variables, I expected path gettemp filename to do the same thing in the sense that the generated filename would be "compliant" with the os and be cleaned by any utility or process that does it. We're talking about 3 different supported os. For osx or Linux I have no clue whether the location or the temp file extension as well is important. I did not investigate the details of it (call me lazy).

So I think you misunderstand. The issue for me is whether if I would create in temp directory a .txt file for example on Linux it would be deleted after x amount of days. Or Linux would only delete .tmp files and leave the txt files for me to handle. Which is why due to my lazyness I just called the net core to get me the temp filename and hoped for the best.

**Comment by bcssov** [comment]
Just to reiterate line of thinking was:
- Irony crashes
- file left on disk
- file gets deleted sometime by the os
I was unsure how other os treat other temp files and not keen to investigate. There never was a problem for me whether the file already existed. Only whether there are some special rules by the other os on treating temp files.
