### ISSUE TITLE
Error on Mac version

### ISSUE THREAD

**Issue by DarelNightinagle** [bcssov/IronyModManager#222]
**Describe the bug**
I've tried to launch IronyModManager on my Mac and got the same error while launching both from terminal or exec file.
[log.docx](https://github.com/bcssov/IronyModManager/files/6224517/log.docx)

**Version:**
 - OS: Mac OS Mojave 10.14.6
 - Irony Version 1.14.35

**Comment by bcssov** [comment]
Thanks for letting me know, turns out it's an upstream issue. The team behind the framework that I use did not properly sync all of their nugets onto the branch. I'll be releasing a new build in a few hours which should fix the issue for you.

I'm going to go ahead and close this ticket, in case of further problems open a new ticket or reactivate this one.
