### ISSUE TITLE
Irony Mod Manager fails to start after closing conflict solver

### ISSUE THREAD

**Issue by hotchkj** [bcssov/IronyModManager#228]
**Describe the bug**
Upon using a specific maximised conflict solver view, Irony then fails to load with a measurement error. Unclear if this is due to the dual monitor setup I have. I do know I had to do this all in a specific order to get to the point where closing the app created a `WindowState` entry with a bunch of `null` entries.

It might be linked to the mods in question, so in case that helps, they are [!!Ariphaos Unofficial Patch (2.8)](https://steamcommunity.com/sharedfiles/filedetails/?id=1995601384) and [Enigmatic Fortress Fix 2.6-2.8](https://steamcommunity.com/sharedfiles/filedetails/?id=2155664805) and essentially these conflict with a bunch of differences in `leviathans`.

**To Reproduce**
1. Unrar portable RAR
2. Run `IronyModManager.exe`
3. Indicate not to check for updates
4. Select `Fluent Dark` style
5. Restart app when prompted
6. Create new collection `My Collection`
7. Add mods to collection
8. Open `Conflict Solver` (note, no dropdown for Advanced etc. appeared; other themes this does appear)
9. Maximise window
10. Browse conflicts, selecting different diff views
11. Hit close button while maximised conflict solver is open
12. Start app again
13. Fatal error dialog box is displayed

**Logs**
[IronyModManager-Logs.zip](https://github.com/bcssov/IronyModManager/files/6266900/IronyModManager-Logs.zip)

**Screenshots**
![errors](https://user-images.githubusercontent.com/10528178/113765991-7a2b6c80-970c-11eb-8f3b-b7fdffea104c.png)

**Workaround**
Delete `%APPDATA%\Roaming\Mario\IronyModManager\Database_1.14.json`

**Version:**
 - OS: Windows 10
 - Irony: 1.14.41.65428

**Comment by bcssov** [comment]
To be honest without the db json it would have been difficult to understand the conditions when this issue occurs. 

Anyway, nulls are not actually the issue here, the thing is that it's expected to be set like this if you hit the right conditions. What was supposed to happen was that the framework would set the values itself at some point during initialization - if I did not set any values for height\width\location (at least it did that when I wrote the logic a year ago). Now what's happening is that the framework under certain conditions does not set initial height\width anymore which in turn causes this error. With the help of you I was able to fix the issue now. Thanks.

> (note, no dropdown for Advanced etc. appeared; other themes this does appear)

That's to be expected actually. You only set it once per collection.
