### ISSUE TITLE
Parser misinterpreting triggers

### ISSUE THREAD

**Issue by LordOfLA** [bcssov/IronyModManager#25]
See https://i.imgur.com/DuafFhB.png

Can repro with the following mods:

Event Horizon Offset Facility (https://steamcommunity.com/sharedfiles/filedetails/?id=2008059495)
Gigastructural Engineering & More (https://steamcommunity.com/sharedfiles/filedetails/?id=1121692237)

**Comment by bcssov** [comment]
- I acknowledge that Event Horizon Offset Facility is a bug. I've accelerated a feature I planned for later a parser map which should be automated. For the time being it is generated and curated manually but I will automated this procedure in 1.2
- Gigastructural engineering is not my fault, my parser don't have file validation and it got confused due to a syntax error in Gigastructural engineering. This you should take up with the author:
00_giga_districts.txt

Produces not using curly bracket:
```
district_squareworld_farms = {
		produces = (
			food = 10
		}
	}
```
