### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Vitalyudin** [bcssov/IronyModManager#258]
Program crashes on startup. It looks like launching IronyModManager.exe, wheeling mouse cursor, process is showed up in task manager and then it closed without opening program window.
Strange there is that yesterday I was using Irony and it worked properly.

**To Reproduce**
1. Launch IronyModManager.exe

**Logs**
[2021-05-20_Error.log](https://github.com/bcssov/IronyModManager/files/6518452/2021-05-20_Error.log)
Also made ProcMon export if it could help:
[Irony Mod Manager Process Monitor.zip](https://github.com/bcssov/IronyModManager/files/6518457/Irony.Mod.Manager.Process.Monitor.zip)

**Version:**
 - OS:  Windows 10 20H2 (build 19042.985)
 - Irony Version 1.16.26

**Comment by Vitalyudin** [comment]
Tried reinstalling, tried using portable version instead of installable and placing it in different place, tried safe mode, don't know how to figure out what's even happened.

**Comment by Vitalyudin** [comment]
Ok, it is working on a fresh Windows installation on VM. But I literally have no clue what's wrong on my live system. If there are any suggestions, I would be glad

**Comment by Vitalyudin** [comment]
Deleted "Mario" folder in AppData/Roaming and Irony started correctly, what a hell. Maybe it could be useful info, Idk.
I'm closing the issue, have a good time.

**Comment by bcssov** [comment]
It's not something that would happen in a real world scenario but I fixed it anyway. It happened because the version that you had did not have the stored language selection, hence the NREs. Probably while you were translating you've had in that install the Russian locale and then in another install you did not which caused the NRE as Irony tried to find the stored Russian localization information.
