### ISSUE TITLE
Automated mod sorting

### ISSUE THREAD

**Issue by Razunter** [bcssov/IronyModManager#299]
**Is your feature request related to a problem? Please describe.**
It would be great to have automated sorting in the similar way that [RimPy](https://steamcommunity.com/sharedfiles/filedetails/?id=1847679158) does it

**Describe the solution you'd like**
RimPy has a user-submitted db of sorting rules that gets updated from time to time.

**Additional context**
![example](https://user-images.githubusercontent.com/362900/134338836-a991e8e4-37de-40a2-b788-a7bf12c2c6b6.png)

**Comment by bcssov** [comment]
Had this discussion multiple times and it kinda always came to this:
1. There's kind of a lack of community support for such a feature
2. Due to stellaris nature it's dubious how much sense it would make

**Comment by Razunter** [comment]
1. Well, RimPy makes it easy to submit these rules. Moderating these submissions could be tricky, though.
2. Ugh, yeah, auto conflict resolver is must-have :/ Tried to make a small mod collection, ~2500 conflicts.

**Comment by bcssov** [comment]
This requires community involvement and Stellaris player base isn't exactly very technical. Which boils down to my initial arguments. As well Stellaris is still developed game with frequent core game changes which become invalidated after every few months.

Conclusion: I had considered this last year but once I got familiar more with stellaris this idea was dropped. Nothing has changed since then. BOSS\LOOT system will probably never be a thing here.
