### ISSUE TITLE
"Merge" feature unable to create the necessary folder

### ISSUE THREAD

**Issue by AlexVSharp** [bcssov/IronyModManager#361]
**Describe the bug**
Pressing "Merge" (either Basic or Compressed mode) displays the "Not Enough Free Space" notification and halts operation.

**Logs**
2022-05-02 18:34:29.8244 Version: 1.21.133+c9af9317c3
OS Description: Linux 5.4.0-109-generic #123-Ubuntu SMP Fri Apr 8 09:10:54 UTC 2022
Runtime Identifier: linuxmint.20.3-x64
 System.IO.DriveNotFoundException: Could not find the drive '/home/User/.local/share/Paradox Interactive/Stellaris/mod/(Merged)CurrentPlaylist'. The drive might not be ready or might not be mapped.
   at System.IO.DriveInfo.CheckStatfsResultAndThrowIfNecessary(Int32 result)
   at System.IO.DriveInfo.get_AvailableFreeSpace()
   at IronyModManager.IO.DriveInfoProvider.GetFreeSpace(String path) in D:\Working\IronyModManager\src\IronyModManager.IO\DriveInfoProvider.cs:line 68

**Resolution:**
The error is related to the program being unable to create the necessary (Merged) folder.
Creating the said folder manually allows the merging operation to proceed.

**Comment by bcssov** [comment]
It's supposed to create but the exception message tells a different story not of a permission to create folder but of a difficulty to read available disk space.

**Comment by AlexVSharp** [comment]
Noticed something:
When I create "(Merged) CollectionName" to allow the operation to proceed, the program doesn't put files into it.
Instead, it creates another "(Merged)_CollectionName" (with an underscore) and merges the files there.

Could this be related?

**Comment by bcssov** [comment]
> Could this be related?

I'm not too sure, it could just make the drive mounted perhaps (Not using linux all the time so my experience is lacking)...

As for underscore, Irony will always replace whitespace with underscore when generating file or folder names so that behavior is to be expected.

**Comment by adriangaro** [comment]
I know this was marked with `wontfix` and close, but from what I see the no space error appears due to the merged modpack folder not existing. If i created the location manually it tried to check the size off, irony managed to merge the modpack.

Maybe a solution would be to create the folder, before trying to check if there is enough size.... or just check the size for the `Stellaris/mod` folder itself instead of the one in which the collection will be merged.

**Comment by bcssov** [comment]
The Irony logic does not check folder(s); it checks the available drive size (available free space on the specified Hard Disk). On windows this would be equivalent to checking whether drive **D** has 20 GB available.

I don't know enough about linux but this case is related to the specified drive not being mounted. So any attempt to even create a folder would surely fail by all logic.

**Comment by SchusterEric** [comment]
The reason this fails under Linux and not under Windows is probably because Linux uses block devices which can be accessed and are treated as a normal file located anywhere in the file system, so unlike Windows when it encounters a path it cannot find it can not assume that it is on the same drive as the parent folder (recursively up to the root, so "d:" for example). So, when the folder that you use to construct the DriveInfo object doesn't exist, it does not know which drive this folder would be on, so it fails with a not mounted error. If this folder was created before (as a "normal" folder, which should be the default) it would know which drive this folder belongs to and report the free space for it.

**Comment by bcssov** [comment]
No the drive should not be created up front, this is a framework issue which should behave consistently through the various OS.

Commenting on old tickets is also not really helpful to get my attention.

**Comment by SchusterEric** [comment]
The problem is that it is not consistent and it could be fixed quite simply by not checking against a folder which we know does not exist yet and instead checking whether the parent folder ("Stellaris/mods" which we know exists) meets the size requirements. (If we create the sub-folder our self, we know that it will be on the same drive as the parent)

**Comment by bcssov** [comment]
That's for MS to fix TBH on their end. At the moment I can workaround it. The implementation is as generic as it gets and should not switch over to parent directory, it should evaluate what I've given to it. So since this is a framework bug one can in the generic implementation temporarily create the directory and then delete it before exiting the procedure which I've done.
