### ISSUE TITLE
Single instance only

### ISSUE THREAD

**Issue by Arkhorse** [bcssov/IronyModManager#405]
One of the things I have sometimes (ok alot) done is open Irony while its already open. With the amount of mods I have it can take up to a minute to load (yes its on a SSD). I would be nice to have the option to check if Irony is already running and instead focus the already running window.

I say option while not knowing if having multiple instances open would be useful to anyone

**Comment by bcssov** [comment]
You must have lots of mods then. I've got maybe 200 subscribed and it takes the first time (cold start) to have it up and running in about 20 seconds.

Anyway, it is recommended to have Irony run as single instance. Multiple instances might conflict if you modify options which is kept to the discretion of the user.

The feasibility of this suggestion is a big maybe though. 

- Irony runs on Linux\OSX and Windows and well there's no universal solution and I'm not keen on implementing it. One could use a lock mechanism perhaps, or check for running processes.
- There's also ton of problems if this is an option in the GUI since one would have to wait for the DI to come to life and some major refactoring I'm not looking forward to
- How one would bring to focus a window on OSX\Linux is beyond me

**Comment by Arkhorse** [comment]
Just to add what we already talked about:

- I have 754 Steam mods (not including any merged or local mods)
- Recent updates to parallel loading has improved this loading alot (now within that 20 seconds you get, usually)

As for how to get single instance to work on OSX/Linux is also not something I have looked into yet. Im sure its possible, as lots of things can only be opened once on both OS arches. 
The ability to have the option could also state that it only works on reloading the program. 
I know the only other program I can read fully (you know which one) used a lock system to prevent multiple instances (at least before the refactor, havnt had the chance to see what he did to that bit in the refactor)

**Comment by bcssov** [comment]
The other problem is that Irony sometimes launches itself a secondary instance to show fatal error window.

**Comment by bcssov** [comment]
Oh, forgot few more caveats for future reference:
1. If a program is killed by task manager (how to ensure that the lock was not leftover) -- needs research
2. Bringing other programs to focus on other OS -- needs research

**Comment by jtharpla** [comment]
I have a different problem related to this...I sometimes open up Irony to edit my current modlist only to minimize it while looking at Steam Workshop  or a text editor. Inevitably I forget I did so and end up opening a second Irony and making changes.  If I later close the second Irony instance and then the first instance, the first instance overwrites my changes reverting my modlist.  This can be quite difficult to correct once it happens as I often don't realize until I load a game in Stellaris and find it utterly broken :-(

**Comment by jtharpla** [comment]
While there are OS specific ways to force a single instance, perhaps a simple warning that another instance is detected as running would work in a more OS-independent manner?

**Comment by bcssov** [comment]
Still the same issue. Irony can run in 2 modes:
1. Manager mode
2. Error message mode

It would be easier to just not spawn at all than to detect whether an existing process is being run in a certain mode by using a file lock approach.

**Comment by bcssov** [comment]
Implemented in 1.26, closing.
