### ISSUE TITLE
Merged mod collection load incorrectly in hoi4

### ISSUE THREAD

**Issue by dv3lood** [bcssov/IronyModManager#415]
**Describe the bug**
The merged mod collection can't be loaded in hoi4.
Then with the same mods and don't merge them, the game run correctly.

**To Reproduce**
1. add some mods that not comflict into the collection.
2. run the game and it works correctly.
3. use merged mods (either in basic or in compress modes) to run the game and it can't be loaded.

**Expected behavior**
The merged mods can be loaded correctly.

**Screenshots**
game with no mods:
![屏幕截图 2022-11-26 210151](https://user-images.githubusercontent.com/6133401/204090284-b6bb6f22-05b6-40f6-a642-0c79022b4f66.png)
![屏幕截图 2022-11-26 205611](https://user-images.githubusercontent.com/6133401/204090289-d824c63c-c1b1-4a35-80e5-e017ab075eda.png)

game with non-merged mods:
![屏幕截图 2022-11-26 205722](https://user-images.githubusercontent.com/6133401/204090317-a3e6b444-d629-44b1-8dcc-d8dd5cd2c4bb.png)
![屏幕截图 2022-11-26 205825](https://user-images.githubusercontent.com/6133401/204090319-ae13be40-7d46-4b1a-8979-7828fa0836c4.png)

game with compress merged mods:
![屏幕截图 2022-11-26 205851](https://user-images.githubusercontent.com/6133401/204090331-92e4e81f-4903-432b-bf92-8f8f59042745.png)
![屏幕截图 2022-11-26 210001](https://user-images.githubusercontent.com/6133401/204090333-516daa8a-cf79-4e46-b892-cc6661c7d4e2.png)

game with basic merged mods:
![屏幕截图 2022-11-26 210029](https://user-images.githubusercontent.com/6133401/204090262-8c1e1cde-d74f-484f-a290-244c9669deb0.png)
![屏幕截图 2022-11-26 210057](https://user-images.githubusercontent.com/6133401/204090344-5ea65edf-3148-4546-95b0-c23e89af9fd5.png)

**Logs**
If the application crashed add error logs related to the crash.

**Version:**
 - OS: Windows
 - Irony Version: 1.24.93

**Additional context**
I've also tested other supported games, and only found this problem in hoi4.
I don't know what to do to find that which thing cause this problem. If somebody needs more information, please tell me how to get that.

**Comment by bcssov** [comment]
NOTE: HOI4 doesn't support modifying the load order. Therefore:
- Disable editing load order and use (I believe ASCII-betical sort) 
- Make compress merge and basic merge behave in the same manner
- If compress merge causes issues disable it for HOI4

**Comment by dv3lood** [comment]
Thanks for your reply.
I've tried the solution, but it didn't work either.

I've done the things below:

disable editing load order
![屏幕截图 2022-11-27 104428](https://user-images.githubusercontent.com/6133401/204117148-a4760e8c-9167-41c1-adbc-3d9569b9fc11.png)

make the basic merge
![屏幕截图 2022-11-27 105123](https://user-images.githubusercontent.com/6133401/204117153-817ad1ed-4432-4d80-a890-9d2b0c206264.png)

and it didn't work.

Then I even tried to use the PDX launcher to run the merged mods, it didn't work either.
![屏幕截图 2022-11-27 105017](https://user-images.githubusercontent.com/6133401/204117168-6ba8a6c0-6d8f-4ba8-a565-8ae7492590f2.png)

I don't know which one cause this problem, the mods I enabled or other things.

**Comment by bcssov** [comment]
These were notes for me, though now that I had a chance to think through. I should probably just leave stuff as is. Merges could allow people to bypass mod load order issues in HOI4 if editing load order directly does not work.

Anyway back to your issue I did investigate it and the problem is that your collection name is in Chinese. This is HOI4 limitation it seems. When you merge mods mod names are prefixed with certain prefix to prevent duplication issue known for all paradox games ie if you have duplicate mods (with the same name) some games refuse to work. So to circumvent this Irony adds prefix to merged mods. It also makes it easier to navigate to know from where a certain mod comes from. 

Using the identical setup such as your but with collection name using latin alphabet characters the game works without problems. I guess you should complain to paradox for this.

Solution for now rename mod collection to use latin alphabet.

**Comment by dv3lood** [comment]
Thanks for your early reply!
I've rename the collection in English and it worked perfectly. It's definitely the reason. Thx for your help.
