### ISSUE TITLE
IMM takes ages to load

### ISSUE THREAD

**Issue by Martmists-GH** [bcssov/IronyModManager#479]
**Describe the bug**

**To Reproduce**
1. Install IronyModManager
2. Wait approx 20 minutes for the window to appear
3. Wait another 15 minutes for the window to finish loading

**Expected behavior**
The window appears in a few seconds at most, and doesn't take forever to finish loading

**Screenshots**
N/A

**Logs**
N/A

**Version:**
 - OS: Arch Linux
 - Irony Version: 1.25.155-1 from AUR

**Additional context**
I only have mods for stellaris, and that amounts to only 768 mods.

**Comment by bcssov** [comment]
Mods on a harddrive or SSD? You do have a lot of mods and loading them should not really take so much time. What are the computer specs?

To just make sure it's not the AUR issue, can you try and download the portable and see if that makes a difference (although unlikely)?

**Comment by Martmists-GH** [comment]
Specs: NVME SSD (WD_BLACK SN770 2TB), 64GB RAM @ 4800 (DDR5), Ryzen 9 7900X @ 5.733

**Comment by bcssov** [comment]
Try the portable variant.

And I assume the mods are all located on an SSD?

**Comment by Martmists-GH** [comment]
All mods are located on that SSD, yes

**Comment by Martmists-GH** [comment]
The delay seems to be comparable, I think it's doing some loading on main thread as the popup asking for permission to check for updates was blank until the main application loaded.

**Comment by bcssov** [comment]
Wayland, xWayland or x11?

I've been running this on Linux Manjaro with no big delays. The guy who made the AUR package did not report any delays. This seems to be related to your driver or hardware configuration.

You can try and adjust some of these linux related options and see if they help out:
https://github.com/bcssov/IronyModManager/blob/6449b324a2f07e69ef97583687015ca52439a788/src/IronyModManager/appSettings.json#L12-L17

**Comment by Martmists-GH** [comment]
This is on x11 with i3wm, I'll give those settings a try.

**Comment by Martmists-GH** [comment]
I've reduced the amount of mods to ~200 and tried every combination of those settings, but nothing seemed to improve it.

**Comment by bcssov** [comment]
That many mods do not cause such a significant delay. The delay at most should be a few seconds. On my windows machine irony launches within 10 seconds with over 100 mods. 

It is down to a framework and hardware, software or driver.

Have you tried these options I pointed out?

You can also try and enable very verbose framework logging so we can review the GUI framework output:
https://github.com/bcssov/IronyModManager/blob/6449b324a2f07e69ef97583687015ca52439a788/src/IronyModManager/appSettings.json#L3

The UI thread as you said "hiccups" which in turn is caused by the framework I'm using. Maybe the upgrade to latest framework version would work in your case but that is not on the timeline yet.
