### ISSUE TITLE
Bitdefender: installer detected as trojan

### ISSUE THREAD

**Issue by arch7** [bcssov/IronyModManager#501]
**Describe the bug**
The windows installer file win-x64-setup.zip is detected "as infected with Trojan.Generic.35566094" by Bitdefender total security.
The same happens for win-x64.zip. 
Tested with multiple random versions: 
- latest v1.26.173 triggers the AV (linux zip file does not trigger the AV)
- v1.26.167 does not trigger the AV
- v1.26.146 does not trigger the AV
- v1.26.64-alpha does not trigger the AV
- v1.26.77-alpha does not trigger the AV
- 1.24 does not trigger the AV (tested a couple of random versions)
- 1.25 does not trigger the AV up to v1.25.161 (tested some random versions)

**To Reproduce**
1. download the installer file
2. open the installler
3. Bitdefender is triggered and deletes the file

**Expected behavior**
It should not be detected as trojan

**Version:**
 - OS: Windows 10 v19045.4046
 - AV: Bitdefender total security Build 27.0.30.140
 - Irony Version [e.g. 1.5.48]

**Comment by bcssov** [comment]
It's a false positive and running around various AVs to whitelist each version is not something I have time for. Feel try to submit as a false positive. When an AV says it'a generic something it thinks something is a virus but not sure.

Could be that these things don't like the component which talks to steam. Source is available you can review what it does otherwise don't know what to tell you.
