### ISSUE TITLE
Better Mod Archive File Validation

### ISSUE THREAD

**Issue by rossol** [bcssov/IronyModManager#76]
[2020-06-03_Error.log](https://github.com/bcssov/IronyModManager/files/4720001/2020-06-03_Error.log)

**Comment by bcssov** [comment]
One of the mods in a zip archive is corrupt. At one of these locations:
1. Documents\Paradox Interactive\Stellaris\mod
2. Subfolder of Documents\Paradox Interactive\Stellaris\mod
3. Stellaris steam workshop directory

I'll add at a later date some better zip archive validation instead of crashing Irony due to this. For the time being locate invalid zip file and remove it manually.

**Comment by bcssov** [comment]
Note to self: As a fallback try also using  ArchiveFactory instead of ReaderFactory as a last ditch effort in reading problematic zip archives.
